# Generated by Django 5.2 on 2025-04-18 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=64)),
                ('proj', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Auth用户验证UserInfo(非默认用户管理)',
                'verbose_name_plural': 'Auth用户验证UserInfo(非默认用户管理)',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo')),
            ],
            options={
                'verbose_name': 'Auth用户验证Token',
                'verbose_name_plural': 'Auth用户验证Token',
            },
        ),
    ]
