# Generated by Django 5.2 on 2025-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=255, unique=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('last_visit', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '页面访问计数',
                'verbose_name_plural': '页面访问计数',
            },
        ),
    ]
