# Generated by Django 5.2 on 2025-04-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_pagevisitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisitcount',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagevisitcount',
            name='last_visit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
